create database cv;

use cv;

DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS EDU_INFO;
DROP TABLE IF EXISTS EXP_INFO;
DROP TABLE IF EXISTS SKILL_INFO;

CREATE TABLE USER_INFO(
	CNIC INTEGER,
	NAME VARCHAR(30) NOT NULL,
	DOB DATE NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PHONE_NO VARCHAR(15) NOT NULL,
	ADDRESS VARCHAR(150) NOT NULL,
	PRIMARY KEY(CNIC));

CREATE TABLE EDU_INFO(
	EDU_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	INSTITUTE VARCHAR(100) NOT NULL,
	FROM_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	MARKS INT NOT NULL,
	PRIMARY KEY(EDU_ID),
	CONSTRAINT EDU_USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO(CNIC));
	
CREATE TABLE EXP_INFO(
	EXP_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	POSITION VARCHAR(30) NOT NULL,
	ORGANIZATION VARCHAR(100) NOT NULL,
	JOIN_DATE DATE NOT NULL,
	RESIGN_DATE DATE NOT NULL,
	PRIMARY KEY(EXP_ID),
	CONSTRAINT EXP_USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO(CNIC));
	
CREATE TABLE SKILL_INFO(
	SKILL_ID INT AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	PRIMARY KEY(SKILL_ID),
	CONSTRAINT SKILL_USER_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO(CNIC));
	
	
	
